#include <furi.h>
#include <furi_hal.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <gui/canvas.h>
/* generated by fbt from .png files in images folder */
#include <themedtictactoe_icons.h>

#include <gui/modules/menu.h>
#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>

#define GRID_DIM 3
#define X        'X'
#define O        'O'
#define EMPTY    'E'

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    //Menu* menu;
    Gui* gui;
    ViewPort* view_port;
    FuriMessageQueue* event_queue;

    bool running;

    int selected_row;
    int selected_col;
    int selected_cell;

    bool turn; //true is x's turn, false is o's turn

    bool check_selected;

    bool winner;
    int x_wins;
    int O_wins;
} TicTacToeApp;

typedef enum {
    EventTypeInput,
    EventTypeTick,
} TicTacToeEventType;

typedef struct {
    TicTacToeEventType type;
    InputEvent input;
} TicTacToeEvent;

// Structure representing each check in the grid UI
typedef struct Check {
    int row;
    int col;
    int x;
    int y;
    char type;
    const Icon* icon;
    const Icon* icon_selected;
    bool is_used;
} Check;

Check grid[GRID_DIM][GRID_DIM] = {
    {//row 0
     {0, 0, 1, 1, EMPTY, &I_not_used, &I_not_used_selected, false},
     {0, 1, 22, 1, EMPTY, &I_not_used, &I_not_used_selected, false},
     {0, 2, 43, 1, EMPTY, &I_not_used, &I_not_used_selected, false}},
    {//row 1
     {1, 0, 1, 22, EMPTY, &I_not_used, &I_not_used_selected, false},
     {1, 1, 22, 22, EMPTY, &I_not_used, &I_not_used_selected, false},
     {1, 2, 43, 22, EMPTY, &I_not_used, &I_not_used_selected, false}},
    {//row 2
     {2, 0, 1, 43, EMPTY, &I_not_used, &I_not_used_selected, false},
     {2, 1, 22, 43, EMPTY, &I_not_used, &I_not_used_selected, false},
     {2, 2, 43, 43, EMPTY, &I_not_used, &I_not_used_selected, false}}};

static void reset_grid(TicTacToeApp* app) {
    for(int row = 0; row < GRID_DIM; row++) {
        for(int col = 0; col < GRID_DIM; col++) {
            Check* check = &grid[row][col];
            check->type = EMPTY;
            check->icon = &I_not_used;
            check->icon_selected = &I_not_used_selected;
            check->is_used = false;
        }
    }
    app->selected_cell = 0;
    app->winner = false;
}

static void check_winner(TicTacToeApp* app) {
    //checl rows
    for(int row = 0; row < GRID_DIM; row++) {
        if(grid[row][0].type != EMPTY && grid[row][0].type == grid[row][1].type &&
           grid[row][0].type == grid[row][2].type) {
            app->winner = true;
            if(grid[row][0].type == X) {
                app->x_wins++;
            } else {
                app->O_wins++;
            }
            return;
        }
    }

    //check cols
    for(int col = 0; col < GRID_DIM; col++) {
        if(grid[0][col].type != EMPTY && grid[0][col].type == grid[1][col].type &&
           grid[0][col].type == grid[2][col].type) {
            app->winner = true;
            if(grid[0][col].type == X) {
                app->x_wins++;
            } else {
                app->O_wins++;
            }
            return;
        }
    }

    //check diagonals
    if(grid[0][0].type != EMPTY && grid[0][0].type == grid[1][1].type &&
       grid[0][0].type == grid[2][2].type) {
        app->winner = true;
        if(grid[1][1].type == X) {
            app->x_wins++;
        } else {
            app->O_wins++;
        }
        return;
    }

    if(grid[0][2].type != EMPTY && grid[0][2].type == grid[1][1].type &&
       grid[0][2].type == grid[2][0].type) {
        app->winner = true;
        if(grid[1][1].type == X) {
            app->x_wins++;
        } else {
            app->O_wins++;
        }
        return;
    }
}

/*
static void select_check_draw_callback(Canvas* canvas, void* ctx) {
}
*/
static void draw_player_wins(Canvas* canvas, TicTacToeApp* app) {
    for(int i = 0; i < 2; i++) {
        int wins = i ? app->x_wins : app->O_wins; //0 = X, 1 = O
        const Icon* number = NULL;
        switch(wins) {
        case 0:
            number = &I_0;
            break;

        case 1:
            number = &I_1;
            break;

        case 2:
            number = &I_2;
            break;

        case 3:
            number = &I_3;
            break;

        case 4:
            number = &I_4;
            break;

        case 5:
            number = &I_5;
            break;

        case 6:
            number = &I_6;
            break;
        case 7:
            number = &I_7;
            break;

        case 8:
            number = &I_8;
            break;

        case 9:
            number = &I_9;
            break;

        default:
            break;
        }

        if(i) {
            canvas_draw_icon(canvas, 105, 14, number);
        } else {
            canvas_draw_icon(canvas, 105, 37, number);
        }
    }
}

// Draw the UI grid, highlighting the selected check
static void draw_callback(Canvas* canvas, void* ctx) {
    TicTacToeApp* app = ctx;
    if(!app->running) return;
    /*
    if(!app->check_selected) {
        select_check_draw_callback(canvas, ctx);
    }
    */

    canvas_draw_icon(canvas, 0, 0, &I_grid);

    for(int row = 0; row < GRID_DIM; row++) {
        for(int col = 0; col < GRID_DIM; col++) {
            Check* check = &grid[row][col];

            bool selected = (row == app->selected_row && col == app->selected_col);

            if(selected) {
                canvas_draw_icon(canvas, check->x, check->y, check->icon);
                canvas_draw_icon(canvas, check->x, check->y, check->icon_selected);
            } else {
                canvas_draw_icon(canvas, check->x, check->y, check->icon);
            }
        }
    }

    canvas_draw_str(canvas, 75, 9, "SCORE");
    canvas_draw_icon(canvas, 75, 11, &I_x);
    canvas_draw_icon(canvas, 75, 33, &I_o);
    canvas_draw_icon(canvas, 99, 16, &I_colon);
    canvas_draw_icon(canvas, 99, 39, &I_colon);
    draw_player_wins(canvas, app);

    if(app->turn) {
        canvas_draw_str(canvas, 75, 62, "Turn: X");
    } else {
        canvas_draw_str(canvas, 75, 62, "Turn: O");
    }
}

static void input_callback(InputEvent* event, void* ctx) {
    furi_assert(ctx);
    FuriMessageQueue* q = ctx;
    TicTacToeEvent ev = {.type = EventTypeInput, .input = *event};
    furi_message_queue_put(q, &ev, 0);
}

static void tic_tac_toe_input_handler(TicTacToeApp* app, InputEvent* ie) {
    check_winner(app);
    if(app->winner || app->selected_cell == (GRID_DIM * GRID_DIM)) {
        reset_grid(app);
    }

    if(ie->key == InputKeyBack && ie->type == InputTypeLong) {
        app->running = false;
        return;
    }

    if(ie->type == InputTypePress) {
        switch(ie->key) {
        case InputKeyUp:
            if(app->selected_row > 0) {
                app->selected_row--;
            }
            break;

        case InputKeyDown:
            if(app->selected_row < GRID_DIM - 1) {
                app->selected_row++;
            }
            break;

        case InputKeyLeft:
            if(app->selected_col > 0) {
                app->selected_col--;
            }
            break;

        case InputKeyRight:
            if(app->selected_col < GRID_DIM - 1) {
                app->selected_col++;
            }
            break;

        case InputKeyOk:
            Check* check = &grid[app->selected_row][app->selected_col];
            if(check->is_used) {
                break;
            }
            check->type = app->turn ? X : O;
            check->icon = app->turn ? &I_x : &I_o;
            check->icon_selected = app->turn ? &I_x_selected : &I_o_selected;
            check->is_used = true;
            app->turn = !app->turn;
            app->selected_cell++;
            break;

        default:
            break;
        }
    }
}

static TicTacToeApp* tic_tac_toe_app_alloc() {
    TicTacToeApp* app = malloc(sizeof(TicTacToeApp));
    furi_assert(app);

    app->gui = furi_record_open(RECORD_GUI);

    app->event_queue = furi_message_queue_alloc(8, sizeof(TicTacToeEvent));

    app->view_port = view_port_alloc();

    app->running = true;
    app->selected_row = 1;
    app->selected_col = 1;
    app->selected_cell = 0;
    app->turn = true;
    app->check_selected = false;

    app->winner = false;
    app->x_wins = 0;
    app->O_wins = 0;

    view_port_draw_callback_set(app->view_port, draw_callback, app);
    view_port_input_callback_set(app->view_port, input_callback, app->event_queue);

    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);
    view_port_enabled_set(app->view_port, true);

    return app;
}

static void tic_tac_toe_app_free(TicTacToeApp* app) {
    furi_assert(app);
    view_port_enabled_set(app->view_port, false);
    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);
    furi_record_close(RECORD_GUI);
    furi_message_queue_free(app->event_queue);
    free(app);
}

int32_t themedtictactoe_app(void* p) {
    UNUSED(p);

    TicTacToeApp* app = tic_tac_toe_app_alloc();
    TicTacToeEvent ev;

    while(app->running) {
        if(furi_message_queue_get(app->event_queue, &ev, FuriWaitForever) == FuriStatusOk) {
            if(ev.type == EventTypeInput) {
                tic_tac_toe_input_handler(app, &ev.input);
            }
        }
    }

    // Cleanup resources before exit
    tic_tac_toe_app_free(app);
    return 0;
}
