#include <furi.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <gui/canvas.h>
/* generated by fbt from .png files in images folder */
#include <themedtictactoe_icons.h>

#define GRID_DIM 3
#define X        'X'
#define O        'O'
#define EMPTY    'E'

// Structure representing each check in the grid UI
typedef struct Check {
    int row;
    int col;
    int x;
    int y;
    char type;
    const Icon* icon;
    const Icon* icon_selected;
    bool is_used;
} Check;

Check grid[GRID_DIM][GRID_DIM] = {
    {//row 0
     {0, 0, 1, 1, EMPTY, &I_not_used, &I_not_used_selected, false},
     {0, 1, 22, 1, EMPTY, &I_not_used, &I_not_used_selected, false},
     {0, 2, 43, 1, EMPTY, &I_not_used, &I_not_used_selected, false}},
    {//row 1
     {1, 0, 1, 22, EMPTY, &I_not_used, &I_not_used_selected, false},
     {1, 1, 22, 22, EMPTY, &I_not_used, &I_not_used_selected, false},
     {1, 2, 43, 22, EMPTY, &I_not_used, &I_not_used_selected, false}},
    {//row 2
     {2, 0, 1, 43, EMPTY, &I_not_used, &I_not_used_selected, false},
     {2, 1, 22, 43, EMPTY, &I_not_used, &I_not_used_selected, false},
     {2, 2, 43, 43, EMPTY, &I_not_used, &I_not_used_selected, false}}};

int selected_row = 1;
int selected_col = 1;
int selected_cell = 0;

bool turn = true; //true is x's turn, false is o's turn

bool winner = false;
int x_wins = 0;
int O_wins = 0;

static void reset_grid() {
    for(int row = 0; row < GRID_DIM; row++) {
        for(int col = 0; col < GRID_DIM; col++) {
            Check* check = &grid[row][col];
            check->type = EMPTY;
            check->icon = &I_not_used;
            check->icon_selected = &I_not_used_selected;
            check->is_used = false;
        }
    }
    selected_cell = 0;
    winner = false;
}

static void check_winner() {
    //checl rows
    for(int row = 0; row < GRID_DIM; row++) {
        if(grid[row][0].type != EMPTY && grid[row][0].type == grid[row][1].type &&
           grid[row][0].type == grid[row][2].type) {
            winner = true;
            if(grid[row][0].type == X) {
                x_wins++;
            } else {
                O_wins++;
            }
            return;
        }
    }

    //check cols
    for(int col = 0; col < GRID_DIM; col++) {
        if(grid[0][col].type != EMPTY && grid[0][col].type == grid[1][col].type &&
           grid[0][col].type == grid[2][col].type) {
            winner = true;
            if(grid[0][col].type == X) {
                x_wins++;
            } else {
                O_wins++;
            }
            return;
        }
    }

    //check diagonals
    if(grid[0][0].type != EMPTY && grid[0][0].type == grid[1][1].type &&
       grid[0][0].type == grid[2][2].type) {
        winner = true;
        if(grid[1][1].type == X) {
            x_wins++;
        } else {
            O_wins++;
        }
        return;
    }

    if(grid[0][2].type != EMPTY && grid[0][2].type == grid[1][1].type &&
       grid[0][2].type == grid[2][0].type) {
        winner = true;
        if(grid[1][1].type == X) {
            x_wins++;
        } else {
            O_wins++;
        }
        return;
    }
}

static void draw_player_wins(Canvas* canvas) {
    for(int i = 0; i < 2; i++) {
        int wins = i ? wins = x_wins : O_wins; //0 = X, 1 = O
        const Icon* number = NULL;
        switch(wins) {
        case 0:
            number = &I_0;
            break;

        case 1:
            number = &I_1;
            break;

        case 2:
            number = &I_2;
            break;

        case 3:
            number = &I_3;
            break;

        case 4:
            number = &I_4;
            break;

        case 5:
            number = &I_5;
            break;

        case 6:
            number = &I_6;
            break;
        case 7:
            number = &I_7;
            break;

        case 8:
            number = &I_8;
            break;

        case 9:
            number = &I_9;
            break;

        default:
            break;
        }

        if(i) {
            canvas_draw_icon(canvas, 105, 14, number);
        } else {
            canvas_draw_icon(canvas, 105, 37, number);
        }
    }
}

// Draw the UI grid, highlighting the selected check
static void draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);

    canvas_draw_icon(canvas, 0, 0, &I_grid);

    for(int row = 0; row < GRID_DIM; row++) {
        for(int col = 0; col < GRID_DIM; col++) {
            Check* check = &grid[row][col];

            bool selected = (row == selected_row && col == selected_col);

            if(selected) {
                canvas_draw_icon(canvas, check->x, check->y, check->icon);
                canvas_draw_icon(canvas, check->x, check->y, check->icon_selected);
            } else {
                canvas_draw_icon(canvas, check->x, check->y, check->icon);
            }
        }
    }

    canvas_draw_str(canvas, 75, 9, "SCORE");
    canvas_draw_icon(canvas, 75, 11, &I_x);
    canvas_draw_icon(canvas, 75, 33, &I_o);
    canvas_draw_icon(canvas, 99, 16, &I_colon);
    canvas_draw_icon(canvas, 99, 39, &I_colon);
    draw_player_wins(canvas);

    if(turn) {
        canvas_draw_str(canvas, 75, 62, "Turn: X");
    } else {
        canvas_draw_str(canvas, 75, 62, "Turn: O");
    }

    check_winner();
    if(winner || selected_cell == (GRID_DIM * GRID_DIM)) {
        reset_grid();
    }

    if(winner) {
        reset_grid();
    }
}

static void input_callback(InputEvent* event, void* ctx) {
    bool* running = ctx;

    if(event->type == InputTypeLong && event->key == InputKeyBack) {
        *running = false;
        return;
    }

    if(event->type != InputTypeShort) {
        return;
    }

    switch(event->key) {
    case InputKeyUp:
        if(selected_row > 0) {
            selected_row--;
        }
        break;

    case InputKeyDown:
        if(selected_row < GRID_DIM - 1) {
            selected_row++;
        }
        break;

    case InputKeyLeft:
        if(selected_col > 0) {
            selected_col--;
        }
        break;

    case InputKeyRight:
        if(selected_col < GRID_DIM - 1) {
            selected_col++;
        }
        break;

    case InputKeyOk:
        Check* check = &grid[selected_row][selected_col];
        if(check->is_used) {
            break;
        }
        check->type = turn ? X : O;
        check->icon = turn ? &I_x : &I_o;
        check->icon_selected = turn ? &I_x_selected : &I_o_selected;
        check->is_used = true;
        turn = !turn;
        selected_cell++;
        break;

    default:
        break;
    }
}

int32_t themedtictactoe_app(void* p) {
    UNUSED(p);

    bool running = true;

    Gui* gui = furi_record_open("gui");

    ViewPort* viewport = view_port_alloc();

    view_port_draw_callback_set(viewport, draw_callback, NULL);
    view_port_input_callback_set(viewport, input_callback, &running);

    gui_add_view_port(gui, viewport, GuiLayerFullscreen);

    while(running) {
        furi_delay_ms(50);
        //view_port_update(viewport);
    }

    // Cleanup resources before exit
    gui_remove_view_port(gui, viewport);
    view_port_free(viewport);
    furi_record_close("gui");

    return 0;
}
